vim.g.mapleader = ' '

require('vux.globals')
require('vux.plugins')

require('vux.options')

require('vux.nvimtree')
require('vux.starrtify')
require('vux.ctrlsf')
-- require('vux.indentline')
require('vux.indent-blankline')
require('vux.easymotion')
require('vux.whitespace')
require('vux.kommentary')
-- require('vux.floatterm')
require('vux.fterm')
require('vux.treesitter')
require('vux.telescope')
require('vux.lsp')
require('vux.lspkind')
-- require('vux.completion')
require('vux.compe')
require('vux.devicons')
require('vux.barbar')
require('vux.galaxyline')
-- require('vux.airline')
-- require('vux.lualine')
require('vux.nvim-autopairs')
require('vux.colorize')

require('vux.keymappings')
