require('vux.globals')
require('vux.plugins')
require('vux.options')
require('vux.nvimtree')
-- require('vux.starrtify')
require('vux.dashboard')
require('vux.ctrlsf')
-- require('vux.indentline')
require('vux.indent-blankline')
-- require('vux.easymotion')
require('vux.hop')
require('vux.whitespace')
require('vux.kommentary')
-- require('vux.floatterm')
-- require('vux.fterm')
require('vux.nvim-toggleterm')
require('vux.treesitter')
require('vux.telescope')
require('vux.lsp')
require('vux.lspkind')
-- require('vux.completion')
require('vux.compe')
require('vux.gitsigns')
require('vux.devicons')
-- require('vux.barbar')
require('vux.statusline')
-- require('vux.airline')
require('vux.nvim-autopairs')
-- require('vux.autotags')
require('vux.colorize')
require('vux.neoscroll')
require('vux.keymappings')
